CREATE TABLE author (
    author_id INT NOT NULL AUTO_INCREMENT,
    author VARCHAR(255) NULL DEFAULT NULL,
	PRIMARY KEY (author_id)
);

CREATE TABLE publisher (
    publisher_id INT NOT NULL AUTO_INCREMENT,
    publishingCompany  VARCHAR(255) NULL DEFAULT NULL,
    PRIMARY KEY (publisher_id)
);
INSERT INTO Author (author) VALUES ('롭 로이드 존스 글');
INSERT INTO Author (author) VALUES ('베네데타 죠프레, 엔리카 루시나 그림');
INSERT INTO Author (author) VALUES ('이혜명 옮김');
INSERT INTO Author (author) VALUES ('원작: 에그박사');
INSERT INTO Author (author) VALUES ('글: 박송이');
INSERT INTO Author (author) VALUES ('그림: 홍종현');
INSERT INTO Author (author) VALUES ('흔한남매 원작');
INSERT INTO Author (author) VALUES ('김언정 글');
INSERT INTO Author (author) VALUES ('차차 그림');
INSERT INTO Author (author) VALUES ('양태석 글');
INSERT INTO Author (author) VALUES ('김효진 그림');
INSERT INTO Author (author) VALUES ('by Roderick Hunt');
INSERT INTO Author (author) VALUES ('llustrations by Alex Brychta');
INSERT INTO Author (author) VALUES ('김미애 지음');
INSERT INTO Author (author) VALUES ('정현지 그림');
INSERT INTO Author (author) VALUES ('원작: 파뿌리');
INSERT INTO Author (author) VALUES ('글: 백승하');
INSERT INTO Author (author) VALUES ('그림: 이정태');
INSERT INTO Author (author) VALUES ('원작·그림: SAMG');
INSERT INTO Author (author) VALUES ('엮음: 아이휴먼 편집부');
INSERT INTO Author (author) VALUES ('글: 박시연');
INSERT INTO Author (author) VALUES ('그림: 최우빈');
INSERT INTO Author (author) VALUES ('by Norman Feuti');
INSERT INTO Author (author) VALUES ('by Norman Feuti');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 백난도');
INSERT INTO Author (author) VALUES ('그림: 유난희');
INSERT INTO Author (author) VALUES ('글: 박시연');
INSERT INTO Author (author) VALUES ('그림: 최우빈');
INSERT INTO Author (author) VALUES ('정인철 글');
INSERT INTO Author (author) VALUES ('윤문영 그림');
INSERT INTO Author (author) VALUES ('정두루 영어 번역');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 백난도');
INSERT INTO Author (author) VALUES ('그림: 유난희');
INSERT INTO Author (author) VALUES ('글: 전은희');
INSERT INTO Author (author) VALUES ('그림: 이유진');
INSERT INTO Author (author) VALUES ('원작: 몬스터 스튜디오');
INSERT INTO Author (author) VALUES ('글: 이람이');
INSERT INTO Author (author) VALUES ('그림: 조예희');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 한은호');
INSERT INTO Author (author) VALUES ('그림: 유희석');
INSERT INTO Author (author) VALUES ('원작: 토깽이네');
INSERT INTO Author (author) VALUES ('글: 잼스토리');
INSERT INTO Author (author) VALUES ('그림: 양선모');
INSERT INTO Author (author) VALUES ('흔한남매 원작');
INSERT INTO Author (author) VALUES ('김언정 글');
INSERT INTO Author (author) VALUES ('차차 그림');
INSERT INTO Author (author) VALUES ('글: 캐런 브라운');
INSERT INTO Author (author) VALUES ('그림: 이펙 코나크 그림');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 안치현');
INSERT INTO Author (author) VALUES ('그림: 유난희');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 안치현');
INSERT INTO Author (author) VALUES ('그림: 유난희');
INSERT INTO Author (author) VALUES ('흔한남매 원작');
INSERT INTO Author (author) VALUES ('김언정 글');
INSERT INTO Author (author) VALUES ('차차 그림');
INSERT INTO Author (author) VALUES ('원작: 민쩌미');
INSERT INTO Author (author) VALUES ('글: 최재연');
INSERT INTO Author (author) VALUES ('콘티: 서후');
INSERT INTO Author (author) VALUES ('그림: 김기수,권수영');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 백난도');
INSERT INTO Author (author) VALUES ('그림: 유난희');
INSERT INTO Author (author) VALUES ('백희나 닥종이 인형');
INSERT INTO Author (author) VALUES ('이선영 글');
INSERT INTO Author (author) VALUES ('최지경 그림');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 백난도');
INSERT INTO Author (author) VALUES ('그림: 유난희');
INSERT INTO Author (author) VALUES ('원작: 파뿌리');
INSERT INTO Author (author) VALUES ('글: 백승하');
INSERT INTO Author (author) VALUES ('그림: 이정태');
INSERT INTO Author (author) VALUES ('by Norman Feuti');
INSERT INTO Author (author) VALUES ('지은이: 에릭 칼');
INSERT INTO Author (author) VALUES ('옮긴이: 스토리랩');
INSERT INTO Author (author) VALUES ('글: 박시연');
INSERT INTO Author (author) VALUES ('그림: 최우빈');
INSERT INTO Author (author) VALUES ('by Heather Ayris Burnell');
INSERT INTO Author (author) VALUES ('illustrated by Hazel Quintanilla');
INSERT INTO Author (author) VALUES ('글: 송도수');
INSERT INTO Author (author) VALUES ('그림: 서정 엔터테인먼트');
INSERT INTO Author (author) VALUES ('원작: 파뿌리');
INSERT INTO Author (author) VALUES ('글: 백승하');
INSERT INTO Author (author) VALUES ('그림: 이정태');
INSERT INTO Author (author) VALUES ('임정진 글');
INSERT INTO Author (author) VALUES ('김무연 그림');
INSERT INTO Author (author) VALUES ('졸자야 투르바트 기획');
INSERT INTO Author (author) VALUES ('김민진 구성');
INSERT INTO Author (author) VALUES ('이진경 그림');
INSERT INTO Author (author) VALUES ('미네시게 신 지음');
INSERT INTO Author (author) VALUES ('전희정 옮김');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 백난도');
INSERT INTO Author (author) VALUES ('그림: 유난희');
INSERT INTO Author (author) VALUES ('숀 해리스 지음');
INSERT INTO Author (author) VALUES ('윤지원 옮김');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 한은호');
INSERT INTO Author (author) VALUES ('그림: 유희석');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 안치현');
INSERT INTO Author (author) VALUES ('그림: 유난희');
INSERT INTO Author (author) VALUES ('천미진 지음');
INSERT INTO Author (author) VALUES ('윤나래 그림');
INSERT INTO Author (author) VALUES ('원작: 에그박사');
INSERT INTO Author (author) VALUES ('글: 박송이');
INSERT INTO Author (author) VALUES ('그림: 홍종현');
INSERT INTO Author (author) VALUES ('소피 뒤소스와 지음');
INSERT INTO Author (author) VALUES ('박대진 옮김');
INSERT INTO Author (author) VALUES ('마크에티엔 펭트르 그림');
INSERT INTO Author (author) VALUES ('글·그림: 신태훈,나승훈');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 백난도');
INSERT INTO Author (author) VALUES ('그림: 유난희');
INSERT INTO Author (author) VALUES ('by Mike Thaler');
INSERT INTO Author (author) VALUES ('illustrated by Jared Lee');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 안치현');
INSERT INTO Author (author) VALUES ('그림: 유난희');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 한은호');
INSERT INTO Author (author) VALUES ('그림: 유희석');
INSERT INTO Author (author) VALUES ('이즈미 마사토 지음');
INSERT INTO Author (author) VALUES ('김윤수 옮김');
INSERT INTO Author (author) VALUES ('글: 박시연');
INSERT INTO Author (author) VALUES ('그림: 최우빈');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 백난도');
INSERT INTO Author (author) VALUES ('그림: 유난희');
INSERT INTO Author (author) VALUES ('원작: 토깽이네');
INSERT INTO Author (author) VALUES ('글: 잼스토리');
INSERT INTO Author (author) VALUES ('그림: 양선모');
INSERT INTO Author (author) VALUES ('샘 태플린 글');
INSERT INTO Author (author) VALUES ('페데리카 아이오사 그림');
INSERT INTO Author (author) VALUES ('글: 정재은');
INSERT INTO Author (author) VALUES ('그림: 김현민');
INSERT INTO Author (author) VALUES ('애런 레이놀즈 글');
INSERT INTO Author (author) VALUES ('피터 브라운 그림');
INSERT INTO Author (author) VALUES ('홍연미 옮김');
INSERT INTO Author (author) VALUES ('흔한남매 원작');
INSERT INTO Author (author) VALUES ('최재훈 글');
INSERT INTO Author (author) VALUES ('정주연 그림');
INSERT INTO Author (author) VALUES ('시바타 케이코 글·그림');
INSERT INTO Author (author) VALUES ('황진희 옮김');
INSERT INTO Author (author) VALUES ('원작: 몬스터 스튜디오');
INSERT INTO Author (author) VALUES ('글: 김승민');
INSERT INTO Author (author) VALUES ('그림: 최우빈');
INSERT INTO Author (author) VALUES ('글: 설민석,스토리박스');
INSERT INTO Author (author) VALUES ('그림: 정현희');
INSERT INTO Author (author) VALUES ('원작: 파뿌리');
INSERT INTO Author (author) VALUES ('글: 백승하');
INSERT INTO Author (author) VALUES ('그림: 이정태');
INSERT INTO Author (author) VALUES ('지은이: 댄 그린');
INSERT INTO Author (author) VALUES ('옮긴이: 김효영');
INSERT INTO Author (author) VALUES ('원작: 파뿌리');
INSERT INTO Author (author) VALUES ('글: 백승하');
INSERT INTO Author (author) VALUES ('그림: 이정태');
INSERT INTO Author (author) VALUES ('지은이: 댄 그린');
INSERT INTO Author (author) VALUES ('옮긴이: 김효영');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 백난도');
INSERT INTO Author (author) VALUES ('그림: 유난희');
INSERT INTO Author (author) VALUES ('원작: 백앤아');
INSERT INTO Author (author) VALUES ('글: 안성훈');
INSERT INTO Author (author) VALUES ('그림: 돌만');
INSERT INTO Author (author) VALUES ('글: 김미영');
INSERT INTO Author (author) VALUES ('그림: 김정한');
INSERT INTO Author (author) VALUES ('글: 박설연');
INSERT INTO Author (author) VALUES ('그림: 김덕영');
INSERT INTO Author (author) VALUES ('by Heather Ayris Burnell');
INSERT INTO Author (author) VALUES ('illustrated by Hazel Quintanilla');
INSERT INTO Author (author) VALUES ('아다치 히로미 글');
INSERT INTO Author (author) VALUES ('가와하라 미즈마루 그림');
INSERT INTO Author (author) VALUES ('권남희 옮김');
INSERT INTO Author (author) VALUES ('글: 채사장,마케마케');
INSERT INTO Author (author) VALUES ('그림: 정용환');
INSERT INTO Author (author) VALUES ('흔한남매 원작');
INSERT INTO Author (author) VALUES ('최재훈 글');
INSERT INTO Author (author) VALUES ('정주연 그림');
INSERT INTO Author (author) VALUES ('글: 김강현');
INSERT INTO Author (author) VALUES ('그림: 김기수');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 이현진,닥터 스코');
INSERT INTO Author (author) VALUES ('그림: 김덕영');
INSERT INTO Author (author) VALUES ('원작: 파뿌리');
INSERT INTO Author (author) VALUES ('글: 백승하');
INSERT INTO Author (author) VALUES ('그림: 이정태');
INSERT INTO Author (author) VALUES ('by Norman Feuti');
INSERT INTO Author (author) VALUES ('원작: 파뿌리');
INSERT INTO Author (author) VALUES ('글: 백승하');
INSERT INTO Author (author) VALUES ('그림: 이정태');
INSERT INTO Author (author) VALUES ('글: 박설연');
INSERT INTO Author (author) VALUES ('그림: 김덕영');
INSERT INTO Author (author) VALUES ('원작: 비마이펫');
INSERT INTO Author (author) VALUES ('만화 구성: 박지영');
INSERT INTO Author (author) VALUES ('글: 송도수');
INSERT INTO Author (author) VALUES ('그림: 서정 엔터테인먼트');
INSERT INTO Author (author) VALUES ('원작: 비마이펫');
INSERT INTO Author (author) VALUES ('만화 구성: 최진규');
INSERT INTO Author (author) VALUES ('황혜영 글');
INSERT INTO Author (author) VALUES ('박현미 그림');
INSERT INTO Author (author) VALUES ('안선영 해설');
INSERT INTO Author (author) VALUES ('강효미 지음');
INSERT INTO Author (author) VALUES ('한지선 그림');
INSERT INTO Author (author) VALUES ('팝콘스토리 글');
INSERT INTO Author (author) VALUES ('한현동 그림');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 백난도');
INSERT INTO Author (author) VALUES ('그림: 유난희');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 백난도');
INSERT INTO Author (author) VALUES ('그림: 유난희');
INSERT INTO Author (author) VALUES ('by Kes Gray');
INSERT INTO Author (author) VALUES ('illustrated by Nick Sharratt');
INSERT INTO Author (author) VALUES ('글: 스토리 a');
INSERT INTO Author (author) VALUES ('그림: 홍종현');
INSERT INTO Author (author) VALUES ('이한나(츄발라) 지음');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 백난도');
INSERT INTO Author (author) VALUES ('그림: 유난희');
INSERT INTO Author (author) VALUES ('원작: 말이야와 친구들');
INSERT INTO Author (author) VALUES ('글: 김정욱');
INSERT INTO Author (author) VALUES ('그림: 이혜림');
INSERT INTO Author (author) VALUES ('흔한남매 원작');
INSERT INTO Author (author) VALUES ('한바리 글');
INSERT INTO Author (author) VALUES ('유난희 그림');
INSERT INTO Author (author) VALUES ('급식왕 원작');
INSERT INTO Author (author) VALUES ('최재연 글');
INSERT INTO Author (author) VALUES ('서후 콘티');
INSERT INTO Author (author) VALUES ('구은미 그림');
INSERT INTO Author (author) VALUES ('루스 퀘일 글');
INSERT INTO Author (author) VALUES ('제즈 투야 그림');
INSERT INTO Author (author) VALUES ('김현희 옮김');
INSERT INTO Author (author) VALUES ('지은이: 손원평');
INSERT INTO Author (author) VALUES ('원작: 에그박사');
INSERT INTO Author (author) VALUES ('글: 박송이');
INSERT INTO Author (author) VALUES ('그림: 홍종현');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 이재국,이현진');
INSERT INTO Author (author) VALUES ('그림: 김덕영');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 안치현');
INSERT INTO Author (author) VALUES ('그림: 유난희');
INSERT INTO Author (author) VALUES ('글: 강효미');
INSERT INTO Author (author) VALUES ('그림: 김무연');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 안치현');
INSERT INTO Author (author) VALUES ('그림: 유난희');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 이현진,닥터 스코');
INSERT INTO Author (author) VALUES ('그림: 김덕영');
INSERT INTO Author (author) VALUES ('글: 김강현');
INSERT INTO Author (author) VALUES ('그림: 김기수');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 한은호');
INSERT INTO Author (author) VALUES ('그림: 유희석');
INSERT INTO Author (author) VALUES ('지은이: 김호연');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 이재국,이현진');
INSERT INTO Author (author) VALUES ('그림: 김덕영');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 안치현');
INSERT INTO Author (author) VALUES ('그림: 유난희');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 백난도');
INSERT INTO Author (author) VALUES ('그림: 유난희');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 이현진,닥터 스코');
INSERT INTO Author (author) VALUES ('그림: 김덕영');
INSERT INTO Author (author) VALUES ('원작: 에그박사');
INSERT INTO Author (author) VALUES ('글: 박송이');
INSERT INTO Author (author) VALUES ('그림: 홍종현');
INSERT INTO Author (author) VALUES ('서울문화사 편');
INSERT INTO Author (author) VALUES ('저자: 김홍신');
INSERT INTO Author (author) VALUES ('임영주');
INSERT INTO Author (author) VALUES ('그림: 조시내');
INSERT INTO Author (author) VALUES ('글: 박시연');
INSERT INTO Author (author) VALUES ('그림: 최우빈');
INSERT INTO Author (author) VALUES ('안은영 글·그림');
INSERT INTO Author (author) VALUES ('오무라 도모코 글·그림');
INSERT INTO Author (author) VALUES ('고향옥 옮김');
INSERT INTO Author (author) VALUES ('존리,예영 글');
INSERT INTO Author (author) VALUES ('정주연 그림');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 백난도');
INSERT INTO Author (author) VALUES ('그림: 유난희');
INSERT INTO Author (author) VALUES ('글: 박시연');
INSERT INTO Author (author) VALUES ('그림: 최우빈');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 한은호');
INSERT INTO Author (author) VALUES ('그림: 유희석');
INSERT INTO Author (author) VALUES ('글: 박시연');
INSERT INTO Author (author) VALUES ('그림: 최우빈');
INSERT INTO Author (author) VALUES ('저자: 올드스테어즈 편집부');
INSERT INTO Author (author) VALUES ('저자: 올드스테어즈 편집부');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 백난도');
INSERT INTO Author (author) VALUES ('그림: 유난희');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 이현진,닥터 스코');
INSERT INTO Author (author) VALUES ('그림: 김덕영');
INSERT INTO Author (author) VALUES ('원작: 토깽이네');
INSERT INTO Author (author) VALUES ('글: 잼스토리');
INSERT INTO Author (author) VALUES ('그림: 양선모');
INSERT INTO Author (author) VALUES ('박보람 글');
INSERT INTO Author (author) VALUES ('송수혜 그림');
INSERT INTO Author (author) VALUES ('악동 김블루 원작');
INSERT INTO Author (author) VALUES ('전판교 글');
INSERT INTO Author (author) VALUES ('이영아 그림');
INSERT INTO Author (author) VALUES ('원작: 에그박사');
INSERT INTO Author (author) VALUES ('글: 박송이');
INSERT INTO Author (author) VALUES ('그림: 홍종현');
INSERT INTO Author (author) VALUES ('글: 미나 레이시');
INSERT INTO Author (author) VALUES ('그림: 샘 브루스터');
INSERT INTO Author (author) VALUES ('옮김: 신인수');
INSERT INTO Author (author) VALUES ('오혜인 글·그림');
INSERT INTO Author (author) VALUES ('윤정주 글·그림');
INSERT INTO Author (author) VALUES ('글: 김정욱');
INSERT INTO Author (author) VALUES ('그림: 김정한');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 노지영');
INSERT INTO Author (author) VALUES ('그림: 도니패밀리');
INSERT INTO Author (author) VALUES ('존리,예영 글');
INSERT INTO Author (author) VALUES ('정주연 그림');
INSERT INTO Author (author) VALUES ('김용세,김병섭 글');
INSERT INTO Author (author) VALUES ('센개 그림');
INSERT INTO Author (author) VALUES ('원작: 하얀오리');
INSERT INTO Author (author) VALUES ('글: 이지에이');
INSERT INTO Author (author) VALUES ('그림: 박지영,이지에이');
INSERT INTO Author (author) VALUES ('글: 강효미');
INSERT INTO Author (author) VALUES ('그림: 김무연');
INSERT INTO Author (author) VALUES ('글·그림: 양작가');
INSERT INTO Author (author) VALUES ('글: 박시연');
INSERT INTO Author (author) VALUES ('그림: 최우빈');
INSERT INTO Author (author) VALUES ('원작·그림: 몬스터스튜디오');
INSERT INTO Author (author) VALUES ('글·그림: 이지');
INSERT INTO Author (author) VALUES ('미레이유 달랑세 글·그림');
INSERT INTO Author (author) VALUES ('파비앙 옮김');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 한은호');
INSERT INTO Author (author) VALUES ('그림: 유희석');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 백난도');
INSERT INTO Author (author) VALUES ('그림: 유난희');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 안치현');
INSERT INTO Author (author) VALUES ('그림: 유난희');
INSERT INTO Author (author) VALUES ('흔한남매 원작');
INSERT INTO Author (author) VALUES ('최재훈 글');
INSERT INTO Author (author) VALUES ('정주연 그림');
INSERT INTO Author (author) VALUES ('원작: 에그박사');
INSERT INTO Author (author) VALUES ('글: 박송이');
INSERT INTO Author (author) VALUES ('그림: 홍종현');
INSERT INTO Author (author) VALUES ('글: 박시연');
INSERT INTO Author (author) VALUES ('그림: 최우빈');
INSERT INTO Author (author) VALUES ('글: 박시연');
INSERT INTO Author (author) VALUES ('그림: 최우빈');
INSERT INTO Author (author) VALUES ('지은이: 김이삭');
INSERT INTO Author (author) VALUES ('그린이: 이효선');
INSERT INTO Author (author) VALUES ('모리스 샌닥 그림/글');
INSERT INTO Author (author) VALUES ('강무홍 옮김');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 이현진,닥터 스코');
INSERT INTO Author (author) VALUES ('그림: 김덕영');
INSERT INTO Author (author) VALUES ('글·그림: 한날');
INSERT INTO Author (author) VALUES ('글: 차유진,정재승');
INSERT INTO Author (author) VALUES ('그림: 김현민');
INSERT INTO Author (author) VALUES ('글: 류미원');
INSERT INTO Author (author) VALUES ('그림: 이경석');
INSERT INTO Author (author) VALUES ('시미즈 글·그림');
INSERT INTO Author (author) VALUES ('김숙 옮김');
INSERT INTO Author (author) VALUES ('글: 채사장,마케마케');
INSERT INTO Author (author) VALUES ('그림: 정용환');
INSERT INTO Author (author) VALUES ('지은이: 김흥식');
INSERT INTO Author (author) VALUES ('글: 김강현');
INSERT INTO Author (author) VALUES ('그림: 김기수');
INSERT INTO Author (author) VALUES ('글: 설민석,김정욱');
INSERT INTO Author (author) VALUES ('그림: 박성일');
INSERT INTO Author (author) VALUES ('글: 강진희');
INSERT INTO Author (author) VALUES ('그림: 김광일');
INSERT INTO Author (author) VALUES ('지은이: 정지아');
INSERT INTO Author (author) VALUES ('글: 안치현');
INSERT INTO Author (author) VALUES ('그림: 강경효');
INSERT INTO Author (author) VALUES ('이현 글');
INSERT INTO Author (author) VALUES ('국민지 그림');
INSERT INTO Author (author) VALUES ('글: 에런 레이놀즈');
INSERT INTO Author (author) VALUES ('그림: 피터 브라운');
INSERT INTO Author (author) VALUES ('옮김: 홍연미');
INSERT INTO Author (author) VALUES ('by Tina Kugler');
INSERT INTO Author (author) VALUES ('구도 노리코 글·그림');
INSERT INTO Author (author) VALUES ('한라경 옮김');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 한은호');
INSERT INTO Author (author) VALUES ('그림: 유희석');
INSERT INTO Author (author) VALUES ('흔한남매 원작');
INSERT INTO Author (author) VALUES ('김언정 글');
INSERT INTO Author (author) VALUES ('차차 그림');
INSERT INTO Author (author) VALUES ('김성범 글');
INSERT INTO Author (author) VALUES ('이경국 그림');
INSERT INTO Author (author) VALUES ('글: 오주영');
INSERT INTO Author (author) VALUES ('그림: 김일경');
INSERT INTO Author (author) VALUES ('캐서린 바');
INSERT INTO Author (author) VALUES ('스티브 윌리엄스 지음');
INSERT INTO Author (author) VALUES ('에이미 허즈번드 그림');
INSERT INTO Author (author) VALUES ('황세림 옮김');
INSERT INTO Author (author) VALUES ('박시연 글');
INSERT INTO Author (author) VALUES ('최우빈 그림');
INSERT INTO Author (author) VALUES ('글: 박시연');
INSERT INTO Author (author) VALUES ('그림: 최우빈');
INSERT INTO Author (author) VALUES ('한라경 글');
INSERT INTO Author (author) VALUES ('홍선주 그림');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 한은호');
INSERT INTO Author (author) VALUES ('그림: 유희석');
INSERT INTO Author (author) VALUES ('지은이: 이미예');
INSERT INTO Author (author) VALUES ('급식왕 원작');
INSERT INTO Author (author) VALUES ('최재연 글');
INSERT INTO Author (author) VALUES ('서후 콘티');
INSERT INTO Author (author) VALUES ('구은미 그림');
INSERT INTO Author (author) VALUES ('원작: 에그박사');
INSERT INTO Author (author) VALUES ('글: 박송이');
INSERT INTO Author (author) VALUES ('그림: 홍종현');
INSERT INTO Author (author) VALUES ('애나 렘키 지음');
INSERT INTO Author (author) VALUES ('김두완 옮김');
INSERT INTO Author (author) VALUES ('흔한남매 원작');
INSERT INTO Author (author) VALUES ('김승자,정미화 글');
INSERT INTO Author (author) VALUES ('투윙스,유영근 그림');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 한은호');
INSERT INTO Author (author) VALUES ('그림: 유희석');
INSERT INTO Author (author) VALUES ('원작: 몬스터 스튜디오');
INSERT INTO Author (author) VALUES ('글: 이람이');
INSERT INTO Author (author) VALUES ('그림: 조예희');
INSERT INTO Author (author) VALUES ('무돌 글·그림');
INSERT INTO Author (author) VALUES ('글: 강효미');
INSERT INTO Author (author) VALUES ('그림: 김무연');
INSERT INTO Author (author) VALUES ('글: 박시연');
INSERT INTO Author (author) VALUES ('그림: 최우빈');
INSERT INTO Author (author) VALUES ('글: 유대영');
INSERT INTO Author (author) VALUES ('그림:홍거북');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 이재국,이현진');
INSERT INTO Author (author) VALUES ('그림: 김덕영');
INSERT INTO Author (author) VALUES ('원작: 토깽이네');
INSERT INTO Author (author) VALUES ('글: 잼스토리');
INSERT INTO Author (author) VALUES ('그림: 양선모');
INSERT INTO Author (author) VALUES ('흔한남매 원작');
INSERT INTO Author (author) VALUES ('김언정 글');
INSERT INTO Author (author) VALUES ('차차 그림');
INSERT INTO Author (author) VALUES ('글: 박시연');
INSERT INTO Author (author) VALUES ('그림:최우빈');
INSERT INTO Author (author) VALUES ('by Michelle Robinson');
INSERT INTO Author (author) VALUES ('지은이: 송현주');
INSERT INTO Author (author) VALUES ('글: 조수연,전판교');
INSERT INTO Author (author) VALUES ('그림: 소윤');
INSERT INTO Author (author) VALUES ('원작: 흔한남매');
INSERT INTO Author (author) VALUES ('글: 이재국,이현진');
INSERT INTO Author (author) VALUES ('그림: 김덕영');
INSERT INTO Author (author) VALUES ('토이트론 편집부 지음');
INSERT INTO Author (author) VALUES ('유대영 글');
INSERT INTO Author (author) VALUES ('홍거북 그림');
INSERT INTO Author (author) VALUES ('토이트론 편집부 지음');



DELETE a1 
FROM 
	Author a1, Author a2 
WHERE 
	a1.author_id > a2.author_id AND a1.author = a2.author;

CREATE TABLE Author_New (
    Author_id INT AUTO_INCREMENT PRIMARY KEY,
    author VARCHAR(255) -- 여기에 적절한 자료형을 사용하세요
);

INSERT INTO Author_New (author)
SELECT DISTINCT author FROM Author;
DROP TABLE Author;

-- new_table을 Author로 이름 변경
ALTER TABLE Author_New RENAME TO Author;


INSERT INTO publisher (publishingCompany) VALUES ('어스본코리아');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('김영사');
INSERT INTO publisher (publishingCompany) VALUES ('Oxford University Press');
INSERT INTO publisher (publishingCompany) VALUES ('위즈덤하우스');
INSERT INTO publisher (publishingCompany) VALUES ('겜툰');
INSERT INTO publisher (publishingCompany) VALUES ('아이휴먼');
INSERT INTO publisher (publishingCompany) VALUES ('아울북');
INSERT INTO publisher (publishingCompany) VALUES ('Scholastic');
INSERT INTO publisher (publishingCompany) VALUES ('Scholastic');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('아울북');
INSERT INTO publisher (publishingCompany) VALUES ('베틀북');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('다림');
INSERT INTO publisher (publishingCompany) VALUES ('대원키즈');
INSERT INTO publisher (publishingCompany) VALUES ('다산어린이');
INSERT INTO publisher (publishingCompany) VALUES ('위즈덤하우스');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('사파리');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('샌드박스스토리키즈');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('한솔수북');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('겜툰');
INSERT INTO publisher (publishingCompany) VALUES ('Scholastic');
INSERT INTO publisher (publishingCompany) VALUES ('시공주니어');
INSERT INTO publisher (publishingCompany) VALUES ('아울북');
INSERT INTO publisher (publishingCompany) VALUES ('Scholastic');
INSERT INTO publisher (publishingCompany) VALUES ('서울문화사');
INSERT INTO publisher (publishingCompany) VALUES ('겜툰');
INSERT INTO publisher (publishingCompany) VALUES ('푸른숲주니어');
INSERT INTO publisher (publishingCompany) VALUES ('아람');
INSERT INTO publisher (publishingCompany) VALUES ('이성과감성');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('지양사');
INSERT INTO publisher (publishingCompany) VALUES ('다산어린이');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('키즈엠');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('보림');
INSERT INTO publisher (publishingCompany) VALUES ('주니어김영사');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('Scholastic Singapore');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('다산어린이');
INSERT INTO publisher (publishingCompany) VALUES ('다산북스');
INSERT INTO publisher (publishingCompany) VALUES ('아울북');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('위즈덤하우스');
INSERT INTO publisher (publishingCompany) VALUES ('어스본코리아');
INSERT INTO publisher (publishingCompany) VALUES ('아울북');
INSERT INTO publisher (publishingCompany) VALUES ('주니어RHK');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('길벗어린이');
INSERT INTO publisher (publishingCompany) VALUES ('대원키즈');
INSERT INTO publisher (publishingCompany) VALUES ('Dankkum i(단꿈아이)');
INSERT INTO publisher (publishingCompany) VALUES ('겜툰');
INSERT INTO publisher (publishingCompany) VALUES ('겜툰');
INSERT INTO publisher (publishingCompany) VALUES ('비룡소');
INSERT INTO publisher (publishingCompany) VALUES ('겜툰');
INSERT INTO publisher (publishingCompany) VALUES ('비룡소');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('Sandbox Story Kids(샌드박스스토리 키즈)');
INSERT INTO publisher (publishingCompany) VALUES ('아울북');
INSERT INTO publisher (publishingCompany) VALUES ('아울북');
INSERT INTO publisher (publishingCompany) VALUES ('Scholastic');
INSERT INTO publisher (publishingCompany) VALUES ('주니어RHK');
INSERT INTO publisher (publishingCompany) VALUES ('돌핀북');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('서울문화사');
INSERT INTO publisher (publishingCompany) VALUES ('주니어김영사');
INSERT INTO publisher (publishingCompany) VALUES ('겜툰');
INSERT INTO publisher (publishingCompany) VALUES ('Scholastic');
INSERT INTO publisher (publishingCompany) VALUES ('Scholastic');
INSERT INTO publisher (publishingCompany) VALUES ('겜툰');
INSERT INTO publisher (publishingCompany) VALUES ('아울북');
INSERT INTO publisher (publishingCompany) VALUES ('서울문화사');
INSERT INTO publisher (publishingCompany) VALUES ('서울문화사');
INSERT INTO publisher (publishingCompany) VALUES ('서울문화사');
INSERT INTO publisher (publishingCompany) VALUES ('다산어린이');
INSERT INTO publisher (publishingCompany) VALUES ('미래엔');
INSERT INTO publisher (publishingCompany) VALUES ('아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('Red Fox');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('Tornado(토네이도)');
INSERT INTO publisher (publishingCompany) VALUES ('bMirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('주니어김영사');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('북이십일 아울북');
INSERT INTO publisher (publishingCompany) VALUES ('사파리');
INSERT INTO publisher (publishingCompany) VALUES ('창비');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('주니어김영사');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('슈크림북');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('주니어김영사');
INSERT INTO publisher (publishingCompany) VALUES ('서울문화사');
INSERT INTO publisher (publishingCompany) VALUES ('다산어린이');
INSERT INTO publisher (publishingCompany) VALUES ('나무옆의자');
INSERT INTO publisher (publishingCompany) VALUES ('주니어김영사');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('주니어김영사');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('서울문화사');
INSERT INTO publisher (publishingCompany) VALUES ('멘토르출판사');
INSERT INTO publisher (publishingCompany) VALUES ('아울북');
INSERT INTO publisher (publishingCompany) VALUES ('천개의바람');
INSERT INTO publisher (publishingCompany) VALUES ('길벗어린이');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('아울북');
INSERT INTO publisher (publishingCompany) VALUES ('다산어린이');
INSERT INTO publisher (publishingCompany) VALUES ('아울북');
INSERT INTO publisher (publishingCompany) VALUES ('Old Stairs');
INSERT INTO publisher (publishingCompany) VALUES ('Old Stairs');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('주니어김영사');
INSERT INTO publisher (publishingCompany) VALUES ('위즈덤하우스');
INSERT INTO publisher (publishingCompany) VALUES ('제제의숲');
INSERT INTO publisher (publishingCompany) VALUES ('위즈덤하우스');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('비룡소인터내셔널');
INSERT INTO publisher (publishingCompany) VALUES ('코이북스');
INSERT INTO publisher (publishingCompany) VALUES ('책읽는곰');
INSERT INTO publisher (publishingCompany) VALUES ('다산어린이');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('꿈터');
INSERT INTO publisher (publishingCompany) VALUES ('대원키즈');
INSERT INTO publisher (publishingCompany) VALUES ('슈크림북');
INSERT INTO publisher (publishingCompany) VALUES ('파란정원');
INSERT INTO publisher (publishingCompany) VALUES ('아울북');
INSERT INTO publisher (publishingCompany) VALUES ('한솔수북');
INSERT INTO publisher (publishingCompany) VALUES ('Bicycle');
INSERT INTO publisher (publishingCompany) VALUES ('북뱅크');
INSERT INTO publisher (publishingCompany) VALUES ('다산어린이');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('아울북');
INSERT INTO publisher (publishingCompany) VALUES ('아울북');
INSERT INTO publisher (publishingCompany) VALUES ('푸른사상');
INSERT INTO publisher (publishingCompany) VALUES ('시공주니어');
INSERT INTO publisher (publishingCompany) VALUES ('주니어김영사');
INSERT INTO publisher (publishingCompany) VALUES ('파란정원');
INSERT INTO publisher (publishingCompany) VALUES ('아울북');
INSERT INTO publisher (publishingCompany) VALUES ('마술피리');
INSERT INTO publisher (publishingCompany) VALUES ('북뱅크');
INSERT INTO publisher (publishingCompany) VALUES ('돌핀북');
INSERT INTO publisher (publishingCompany) VALUES ('씨드북');
INSERT INTO publisher (publishingCompany) VALUES ('서울문화사');
INSERT INTO publisher (publishingCompany) VALUES ('단꿈아이');
INSERT INTO publisher (publishingCompany) VALUES ('다산어린이');
INSERT INTO publisher (publishingCompany) VALUES ('창비');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('비룡소');
INSERT INTO publisher (publishingCompany) VALUES ('토토북');
INSERT INTO publisher (publishingCompany) VALUES ('Scholastic');
INSERT INTO publisher (publishingCompany) VALUES ('책내음');
INSERT INTO publisher (publishingCompany) VALUES ('다산어린이');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('미래M&B');
INSERT INTO publisher (publishingCompany) VALUES ('루크하우스');
INSERT INTO publisher (publishingCompany) VALUES ('노란돼지');
INSERT INTO publisher (publishingCompany) VALUES ('북이십일 아울북');
INSERT INTO publisher (publishingCompany) VALUES ('아울북');
INSERT INTO publisher (publishingCompany) VALUES ('책내음');
INSERT INTO publisher (publishingCompany) VALUES ('다산어린이');
INSERT INTO publisher (publishingCompany) VALUES ('팩토리나인');
INSERT INTO publisher (publishingCompany) VALUES ('북이십일 아울북');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('흐름출판');
INSERT INTO publisher (publishingCompany) VALUES ('대원키즈');
INSERT INTO publisher (publishingCompany) VALUES ('다산어린이');
INSERT INTO publisher (publishingCompany) VALUES ('대원키즈');
INSERT INTO publisher (publishingCompany) VALUES ('노란돼지');
INSERT INTO publisher (publishingCompany) VALUES ('슈크림북');
INSERT INTO publisher (publishingCompany) VALUES ('북이십일 아울북');
INSERT INTO publisher (publishingCompany) VALUES ('아울북');
INSERT INTO publisher (publishingCompany) VALUES ('주니어김영사');
INSERT INTO publisher (publishingCompany) VALUES ('위즈덤하우스');
INSERT INTO publisher (publishingCompany) VALUES ('Mirae N 아이세움');
INSERT INTO publisher (publishingCompany) VALUES ('북이십일 아울북');
INSERT INTO publisher (publishingCompany) VALUES ('Penguin Young Readers Group');
INSERT INTO publisher (publishingCompany) VALUES ('반달');
INSERT INTO publisher (publishingCompany) VALUES ('다산어린이');
INSERT INTO publisher (publishingCompany) VALUES ('주니어김영사');
INSERT INTO publisher (publishingCompany) VALUES ('토이트론');
INSERT INTO publisher (publishingCompany) VALUES ('아울북');
INSERT INTO publisher (publishingCompany) VALUES ('토이트론');

DELETE p1 
FROM 
	publisher p1, publisher p2 
WHERE 
	p1.publisher_id > p2.publisher_id AND p1.publisher_id = p2.publisher_id;

CREATE TABLE publisher_new (
    publisher_id INT AUTO_INCREMENT PRIMARY KEY,
    publishingCompany VARCHAR(255) -- 여기에 적절한 자료형을 사용하세요
);

INSERT INTO publisher_new (publishingCompany)
SELECT DISTINCT publishingCompany FROM publisher;
DROP TABLE publisher;

-- new_table을 Author로 이름 변경
ALTER TABLE publisher_new RENAME TO publisher;

-- CREATE TABLE BookAuthors (
--     book_id INT,
--     author_id INT,
--     PRIMARY KEY (book_id, author_id),
--     FOREIGN KEY (book_id) REFERENCES book(book_id),
--     FOREIGN KEY (author_id) REFERENCES author(author_id)
-- );

-- CREATE TABLE BookPublishers (
--     book_id INT,
--     publisher_id INT,
--     PRIMARY KEY (book_id, publisher_id),
--     FOREIGN KEY (book_id) REFERENCES book(book_id),
--     FOREIGN KEY (publisher_id) REFERENCES publisher(publisher_id)
-- );

-- INSERT INTO BookAuthors (book_id, author_id) VALUES
-- (1, 1), 
-- (1, 2),
-- (2, 3), 
-- (3, 4),
-- (3, 5); 